# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/isshi/Documents/Lectures/ex3/ex3_2025/FPGA/ex3_rv32_2025/ex3_rv32_2025.srcs/sources_1/bd/rv32/ip/rv32_clk_wiz_0/rv32_clk_wiz_0.xci
# IP: The module: 'rv32_clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/isshi/Documents/Lectures/ex3/ex3_2025/FPGA/ex3_rv32_2025/ex3_rv32_2025.gen/sources_1/bd/rv32/ip/rv32_clk_wiz_0/rv32_clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'rv32_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/isshi/Documents/Lectures/ex3/ex3_2025/FPGA/ex3_rv32_2025/ex3_rv32_2025.gen/sources_1/bd/rv32/ip/rv32_clk_wiz_0/rv32_clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'rv32_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/isshi/Documents/Lectures/ex3/ex3_2025/FPGA/ex3_rv32_2025/ex3_rv32_2025.gen/sources_1/bd/rv32/ip/rv32_clk_wiz_0/rv32_clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rv32_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/isshi/Documents/Lectures/ex3/ex3_2025/FPGA/ex3_rv32_2025/ex3_rv32_2025.srcs/sources_1/bd/rv32/ip/rv32_clk_wiz_0/rv32_clk_wiz_0.xci
# IP: The module: 'rv32_clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/isshi/Documents/Lectures/ex3/ex3_2025/FPGA/ex3_rv32_2025/ex3_rv32_2025.gen/sources_1/bd/rv32/ip/rv32_clk_wiz_0/rv32_clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'rv32_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/isshi/Documents/Lectures/ex3/ex3_2025/FPGA/ex3_rv32_2025/ex3_rv32_2025.gen/sources_1/bd/rv32/ip/rv32_clk_wiz_0/rv32_clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'rv32_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/isshi/Documents/Lectures/ex3/ex3_2025/FPGA/ex3_rv32_2025/ex3_rv32_2025.gen/sources_1/bd/rv32/ip/rv32_clk_wiz_0/rv32_clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rv32_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
