# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/isshi/Documents/Lectures/ex3/ex3_2025/FPGA/ex3_rv32_2025/Nexys-A7-100T-Master.xdc

# Block Designs: bd/rv32/rv32.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rv32 || ORIG_REF_NAME==rv32} -quiet] -quiet

# IP: bd/rv32/ip/rv32_RV32I_SOC_ARCH1_0_0/rv32_RV32I_SOC_ARCH1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rv32_RV32I_SOC_ARCH1_0_0 || ORIG_REF_NAME==rv32_RV32I_SOC_ARCH1_0_0} -quiet] -quiet

# IP: bd/rv32/ip/rv32_clk_wiz_0/rv32_clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rv32_clk_wiz_0 || ORIG_REF_NAME==rv32_clk_wiz_0} -quiet] -quiet

# IP: bd/rv32/ip/rv32_reset_gen_0_0/rv32_reset_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rv32_reset_gen_0_0 || ORIG_REF_NAME==rv32_reset_gen_0_0} -quiet] -quiet

# IP: bd/rv32/ip/rv32_reset_inv_0_0/rv32_reset_inv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rv32_reset_inv_0_0 || ORIG_REF_NAME==rv32_reset_inv_0_0} -quiet] -quiet

# XDC: c:/Users/isshi/Documents/Lectures/ex3/ex3_2025/FPGA/ex3_rv32_2025/ex3_rv32_2025.gen/sources_1/bd/rv32/rv32_ooc.xdc
